### ISSUE TITLE
how shall we plan 4.0?

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#1016]
it seems like we're nearing some kind of critical mass on CLI (and maybe API) breaking changes that would need to be in a new major release.

@luizirber really likes the notion of just doing lots of releases, which I'm on board with? but it seems like maybe doing 4.0, 5.0, and 6.0 in rapid succession would just be confusing :).

but we also don't want to wait forever for a 4.0 because I have the attention span of a gnat, etc. etc. and often don't follow through on medium term plans.

so how can we best collate these features and be poised to release a 4.0 that includes a bunch of new stuff, without blocking on too many features?

my naivest thought is to put a pre-4.0 branch in place that has the same branch protections as master - basically, merges must be reviewed, pass all tests, etc. Have a standing PR for this into master.

alternatively, we can switch 3.x over to a maintenance branch and make master the 4.0. I kinda like this more, actually.

a much worse idea seems to be to have a bunch of hanging PRs that wait to be merged until we're ready to release 4.0. let's not do this.

**Comment by luizirber** [comment]
> alternatively, we can switch 3.x over to a maintenance branch and make master the 4.0. I kinda like this more, actually.

That was the plan for 2 -> 3, but ended up not being necessarily because we moved quickly. I prefer this one to the other alternatives.

> a much worse idea seems to be to have a bunch of hanging PRs that wait to be merged until we're ready to release 4.0. let's not do this.

Somewhat related to this: some current PRs involved a lot of work and may be better to merge them before 4.x (and breaking changes), to avoid large rewrites/rebase/merging changes. #925 comes to mind.

> it seems like we're nearing some kind of critical mass on CLI (and maybe API) breaking changes that would need to be in a new major release.
> so how can we best collate these features and be poised to release a 4.0 that includes a bunch of new stuff, without blocking on too many features?

I like using labels and milestones for tracking. Not that many of them are marked, maybe do another check on opened issues and label them?

- Issues tagged 4.0: https://github.com/dib-lab/sourmash/issues?q=is%3Aopen+is%3Aissue+label%3A4.0
- Milestone 4.0: https://github.com/dib-lab/sourmash/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0

From those, see which ones are actually breaking, and which ones are big chances/refactors that are not necessarily breaking. Some that come to mind:
- #680 is a big change (but not breaking)
- #318 will be breaking for Python 2
- #441 is breaking (remove functionality)
Maybe create a label "breaking" and mark them? And mark the non-breaking ones as "enhancement"?

**Comment by olgabot** [comment]
> > a much worse idea seems to be to have a bunch of hanging PRs that wait to be merged until we're ready to release 4.0. let's not do this.
> 
> Somewhat related to this: some current PRs involved a lot of work and may be better to merge them before 4.x (and breaking changes), to avoid large rewrites/rebase/merging changes. #925 comes to mind.
> 


If 4.0 comes and #925 is not ready, that's okay. I haven't had time to finish it lately but I can take a crack at it this weekend. Will try to get it in before #680!

**Comment by ctb** [comment]
per #1034, we'll go with `latest` (for 4.x and beeeeeyond) and `stable` (for 3.x) branches.

**Comment by ctb** [comment]
with https://github.com/dib-lab/sourmash/pull/1144, we now have

https://github.com/dib-lab/sourmash/releases/tag/v4.0.0a0

and `pip install -e .` produces:
```
% sourmash info

== This is sourmash version 4.0.0a0. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

sourmash version 4.0.0a0
- loaded from path: /Users/t/dev/sourmash/sourmash/cli
```
huzzah!

**Comment by luizirber** [comment]
From https://github.com/dib-lab/sourmash/pull/1128#issuecomment-669326248

> In any case, we might need a PR derived from this one for the `DeprecationWarning`s and merge it in stable? (and then release it as 3.4.2 and continue updating latest? =])

Should we start just adding the `DeprecationWarning`s to `stable` and release patch versions (`3.4.2`, `3.4.3`...) to indicate what is going to break in `4.x`? And maybe make a final `3.5.0` release right before we release `4.0.0`?

**Comment by ctb** [comment]
On Wed, Aug 05, 2020 at 10:31:55AM -0700, Luiz Irber wrote:
> >From https://github.com/dib-lab/sourmash/pull/1128#issuecomment-669326248
> 
> > In any case, we might need a PR derived from this one for the `DeprecationWarning`s and merge it in stable? (and then release it as 3.5.1 and continue updating latest? =])
> 
> Should we start just adding the `DeprecationWarning`s to `stable` and release patch versions (`3.5.1`, `3.5.2`...) to indicate what is going to break in `4.x`?

yes, all sounds good.

**Comment by ctb** [comment]
ok, so the #1128 merge was not done well... I merged into `stable` and then from there into `latest`. I think I prefer:

* merge new PRs into `latest`, with full review etc.
* backport into `stable` periodically as a separate PR, with clear indications of what the original PR or PRs were.

**Comment by luizirber** [comment]
Yeah, `latest` first and then `stable`. I assumed it was against `latest`, but later noticed it was against `stable` :disappointed:

**Comment by ctb** [comment]
On Wed, Aug 05, 2020 at 06:01:47PM -0700, Luiz Irber wrote:
> Yeah, `latest` first and then `stable`. I assumed it was against `latest`, but later noticed it was against `stable` :disappointed: 

I, err, changed it to stable <cringe>

**Comment by ctb** [comment]
OK so I'm slowly starting to figure this out, sigh. I'll release 3.5.0 sometime soon.

**Comment by ctb** [comment]
Note https://github.com/dib-lab/sourmash/releases/tag/v3.5.0a0 (based on `stable`), which should alert us to all the deprecations.

**Comment by luizirber** [comment]
> Note https://github.com/dib-lab/sourmash/releases/tag/v3.5.0a0 (based on `stable`), which should alert us to all the deprecations.

Let's try to avoid too many `a0` versions, I still remember the many `2.0.0a` releases...

**Comment by luizirber** [comment]
I think it is OK for `4.0.0a0`, but let's try to release `3.5.0` soon =]

**Comment by ctb** [comment]
On Thu, Aug 06, 2020 at 09:50:26AM -0700, Luiz Irber wrote:
> I think it is OK for `4.0.0a0`, but let's try to release `3.5.0` soon =]

yes, I did it so that I could get the deprecations working in pytest!

**Comment by luizirber** [comment]
From https://github.com/dib-lab/sourmash/pull/1150#issuecomment-670181539:

> Looks good, overall. Question: do we want to point at `stable` URLs for documentation, notebooks, etc? I expect we'll keep stable up to date with the last release, in the future...

> I thought `stable` was temporary until `4.0.0` is released, keep syncing branches will be annoying... Maybe turn `stable` into a tag, and add to the release notes to replace it on every stable release?

**Comment by ctb** [comment]
any comments on the header, @luizirber ? https://github.com/dib-lab/sourmash/issues/1162 --

This is the first of several minor releases (v3.5.x) from the new `stable` branch that focus on preparing for sourmash v4.0 by introducing deprecations and warnings.

**Comment by ctb** [comment]
some thoughts on next steps towards 3.5.1 and 4.0:

- [x] once #1308 and https://github.com/dib-lab/sourmash/pull/1317 are merged, release 3.5.1 ([release notes](https://github.com/dib-lab/sourmash/issues/1327))
- [x] finish docs #1283 #1092 #919 #1293 #973 and release notes #1309
- [ ] merge #1283 and release 4.0.0a4
- [ ] update author list #622 #444
- [ ] release 4.0 ([release notes](https://github.com/dib-lab/sourmash/issues/1309))
- [ ] adjust conda packaging #1163 #1299

**Comment by ctb** [comment]
reupping question: 
What do we do about stable vs latest docs, per comment above? https://github.com/dib-lab/sourmash/issues/1016#issuecomment-670182317

>Question: do we want to point at stable URLs for documentation, notebooks, etc? I expect we'll keep stable up to date with the last release, in the future...
> I thought stable was temporary until 4.0.0 is released, keep syncing branches will be annoying... Maybe turn stable into a tag, and add to the release notes to replace it on every stable release?

**Comment by ctb** [comment]
ok, I finally grappled with read the docs & stable conversation and I think I understood it!

here's what I think we should do, mechanistically:
* now: shift default readthedocs to redirect to stable (v3.5.1 docs); visiting `sourmash.rtfd.io` will go to stable docs.
* merge #1283, the big doc update for 4.0. it will show up on `sourmash.rtfd.io/en/latest/`, but not be the default docs
* release 3.5.1 and 4.0.0a4
* (do other stuff here)
* release 4.0
* point 'stable' docs at 'latest' now, spin off 3.5.1 docs to their own URL.

that way `stable` always points at the docs you get when you run pip install or conda install without a specific version.

**Comment by luizirber** [comment]
> here's what I think we should do, mechanistically:

I agree, some additional comments:

> * now: shift default readthedocs to redirect to stable (v3.5.1 docs); visiting `sourmash.rtfd.io` will go to stable docs.
> * merge #1283, the big doc update for 4.0. it will show up on `sourmash.rtfd.io/en/latest/`, but not be the default docs
> * release 3.5.1 and 4.0.0a4

I think we can release `4.0.0rc1` instead of another alpha, I think there are no code changes left.

> * (do other stuff here)

Probably debug the migration docs from #1283 and recommend specifying sourmash versions using ranges (`sourmash >=3, <4`), like we do for [setuptools_scm](https://github.com/dib-lab/sourmash/blob/128e50c1b417cd47f897b51843b780987e30a389/pyproject.toml#L4) in `pyproject.toml`

I think we should announce the availability of the migration docs and `4.0.0rc1` and ask for feedback, and after some time (a week?) promote the `rc` to the final release.

> * release 4.0
> * point 'stable' docs at 'latest' now, spin off 3.5.1 docs to their own URL.

And probably remove the `stable` branch?

**Comment by ctb** [comment]
> > here's what I think we should do, mechanistically:
> 
> I agree, some additional comments:
> 
> > * now: shift default readthedocs to redirect to stable (v3.5.1 docs); visiting `sourmash.rtfd.io` will go to stable docs.

**done**! :tada:

> > * merge #1283, the big doc update for 4.0. it will show up on `sourmash.rtfd.io/en/latest/`, but not be the default docs
> > * release 3.5.1 and 4.0.0a4
> 
> I think we can release `4.0.0rc1` instead of another alpha, I think there are no code changes left.

sure!

> > * (do other stuff here)
> 
> Probably debug the migration docs from #1283 and recommend specifying sourmash versions using ranges (`sourmash >=3, <4`), like we do for [setuptools_scm](https://github.com/dib-lab/sourmash/blob/128e50c1b417cd47f897b51843b780987e30a389/pyproject.toml#L4) in `pyproject.toml`

:+1: - I take it that's a suggestion for #1283? 😉 

> I think we should announce the availability of the migration docs and `4.0.0rc1` and ask for feedback, and after some time (a week?) promote the `rc` to the final release.

👍 
 
> > * release 4.0
> > * point 'stable' docs at 'latest' now, spin off 3.5.1 docs to their own URL.
> 
> And probably remove the `stable` branch?

I'd like to keep a v3.5 maint branch around Just In Case? Although we could just start with the v3.5.1 tag if we needed to release a v3.5.2. So :+1: for removal.

**Comment by ctb** [comment]
OK - I think the next step is merging #1283 and then I can release 4.0.0rc1!

**Comment by ctb** [comment]
next steps:

- [x] once #1308 and https://github.com/dib-lab/sourmash/pull/1317 are merged, release 3.5.1 ([release notes](https://github.com/dib-lab/sourmash/issues/1327))
- [x] finish docs #1283 #1092 #919 #1293 #973 and release notes #1309
- [x] merge #1283 and release 4.0.0rc1
- [x] update author list #622 #444
- [x] release 4.0 ([release notes](https://github.com/dib-lab/sourmash/issues/1309))
- [x] adjust conda packaging #1163 #1299
- [x] point default readthedocs at latest again
- [x] remove `stable` branch

**Comment by ctb** [comment]
c'est fini!
