### ISSUE TITLE
what's needed for a 2.0 release?

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#174]
@brooksph and @taylorreiter both think it's time to get the new functionality out there. what's needed for a 2.0 release?

I think we kinda need to wait for a khmer release given our dependency there.

I'd like to do another JOSS paper but that can be 2.0.1 or something.

**Comment by brooksph** [comment]
#146

**Comment by ctb** [comment]
and #168 (add `--protein` to compare), #167 (add `--csv` to compare), #165 (add version output somewhere), maybe #151 (`--rna`), maybe #132 (output names), definitely #127 (properly calculate containment), #105 (load single signatures), and probably #58 (change default signature type away from mrnaseq / omit altogether)

**Comment by luizirber** [comment]
I created a project to track this: https://github.com/dib-lab/sourmash/projects/1

I would also like to add 
- #166 (support storages other than local fs)
- #176 (self-repairing SBTs, since I think it might need a version bump on SBTs)

#177 and #164 don't really change the command line, but I think they are good to get in on the Python API side.

**Comment by ctb** [comment]
#200 needs to be addressed somehow.

**Comment by ctb** [comment]
Also

- [ ] #231 reorder search/gather arguments
- [ ] #223 update documentation with R code
- [ ] #239 report md5 hashes in search
- [ ] #215 results => stdout instead of stderr
- [ ] #213 remove YAML parsing
- [ ] #212 remove cardinality stuff
- [ ] #201 sourmash utils hooks
- [ ] #197 verify fix to inclusion reporting
- [ ] #200 fix SBT search --best-only to deal with comparison
- [ ] #196 signature merge
- [ ] #192 documentation update
- [ ] #189 check ksize on SBT stuff at load (before search)
- [ ] #178 krona output format
- [ ] #173 setuptools version
- [ ] #165 sourmash info
- [ ] #159 docs pointer
- [ ] #180 with abundance/quantification stuff
- [ ] #105 single sig extract
- [ ] #37 YAML foo
- [ ] #58 signature type
- [ ] #230 track source of genomes in SBTs/signatures

**Comment by taylorreiter** [comment]
I think supporting krona output is not necessarily the way to go. Perhaps instead outputting NCBI taxonomy number would be a better use of time, so that it's easy for people to feed their results in to a lot of downstream analyses, not just krona.

I like the Krona visualization, but it is glitchy with large-ish datasets (RNAseq, 4M reads).

**Comment by ctb** [comment]
hi @taylorreiter could you please put the comment re krona over on #178, and perhaps link to the taxonomy issue, #195?

**Comment by ctb** [comment]
also:

- [ ] merge in spacegraphcats fixes, #199

**Comment by luizirber** [comment]
Should we try to tick as many boxes as possible from this checklist? http://python.apichecklist.com/
(probably a better goal for 3.0?)

**Comment by taylorreiter** [comment]
`sourmash lca` output is compatible with krona. I don't think it's useful to have a krona visual for `gather` output.

**Comment by ctb** [comment]
(Everything above that was unchecked was transferred into this issue)

## Python cleanup/new functionality

- [ ] #176 (self-repairing SBTs, since I think it might need a version bump on SBTs)
- [ ] #177 and #164 don't really change the command line, but I think they are good to get in on the Python API side.
- [ ] #401 add info to LCA DB

## Documentation

- [ ] #223 update documentation with R code
- [ ] #159 docs pointer
- [ ] #393 - documentation/tutorial stuff
- [ ] #329 - API docs
- [ ] #400 - LCA commands
- [ ] #313 - add blog posts
- [ ] #297 - sourmash compare
- [ ] #294 - comparing metagenomes help
- [ ] #273 - preparing data for sourmash with khmer
- [ ] #254 - matplotlib DISPLAY issue to known issues
- [ ] #238 - document --scaled
- [ ] #196 signature merge -> docs
- [ ] #159 - docs pointer

## Minor new functionality/fixes

- [ ] #378 - add `--scaled` to downsample when doing `index`
- [ ] #352 - reporting on `sourmash compute`
- [ ] #344 - cleaner logging
- [ ] #259 - add CITATION info
- [ ] maybe #132 (output names)

## Due diligence

- [ ] #370 - error message when comparing 'num' sig to 'scaled' sig
- [ ] #363 - check sbt search with num instead of scaled
- [ ] #312 - check that SBTs are movable
- [ ] #173 - setuptools version

## Punt to 3.x (proposed)

- [ ] #230 track source of genomes in SBTs/signatures 
- [ ] maybe #151 (`--rna`)
- [ ] #201 sourmash utils hooks

## Other release-level work

- [ ] #402 make new databases for search, LCA, etc.

**Comment by ctb** [comment]
For the 2.0 release, it looks like we need --

* some new notebooks #430
* to add citation information #259 

and that's it!

Then finish and merge #592, and then cut a release, I think?

After that I'd like to submit 2.0.0 to JOSS along with all the other stuff we're writing up.

**Comment by luizirber** [comment]
I think we should merge #615 before 2.0 too

**Comment by ctb** [comment]
ok, let me know when it's ready!

**Comment by ctb** [comment]
all done!

now working on final stuff, #622 author list and #623 change logs/release notes.

**Comment by ctb** [comment]
#607 removes a bunch of outdated files. And we'll need to merge #592 right at the time of 2.0 release.

**Comment by ctb** [comment]
ok, I think we're down to:

- [ ] #631 update  documentation, add notebooks, remove old notebooks & files
- [ ] #622 author list
- [ ] #630 change logs/release notes 

and then I think that's that!

**Comment by ctb** [comment]
I mean, after that I want to submit to JOSS too :)

**Comment by ctb** [comment]
looks like author list is it!
