### ISSUE TITLE
Make a release checklist for sourmash

### ISSUE THREAD

**Issue by ctb** [dib-lab/sourmash#27]
Addresses #9, #11, #12, #24, 23, 

- [x] cut new release on github & zenodo
- [x] push to test pypi
- [x] install with pip on empty ubuntu machine, w/in virtualenv & w/root
- [x] test extras: test, doc, demo

**Comment by ctb** [comment]
done! at http://sourmash.readthedocs.io/en/latest/release.html
